### ISSUE TITLE
catalog all third party dependencies

### ISSUE THREAD

**Issue by barzerman** [barzerman/zobot#17]
there's a bunch of semi-standard pip stuff the code currently depends on:
`pqdict`, `pylru`, `flask` ... there might be something else
- create a file listing all of these dependencies
- a script which uses the file to install all required dependencies

**Comment by 0-1-0** [comment]
1. [save dependencies] pip freeze > requirements.txt

## 2. [install dependencies] pip install -r requirements.txt

If you do not have virtual environment  yet:

pip install virtualenv
cd zobot
virtualenv venv
source venv/bin/activate
pip install -r requirements.txt
